### ISSUE TITLE
vault.py causes ansible >=2.3 to throw errors upon playbook execution

### ISSUE THREAD

**Issue by mattlan** [ahes/ansible-filter-vault#1]
To be clear, this happens just having the file in my filter_plugins directory, in this case I am not actively making any calls to the plugin itself.  This is the error that is thrown at the start of playbook execution:

`ERROR! the field 'name' has an invalid value (False), and could not be converted to an string. Error was: get_config() got an unexpected keyword argument 'ispath'`

I was able to workaround this by changing the below, though I haven't done any extensive testing.  I just wanted to raise this as a heads up.

```
- VAULT_FILTER_KEY = C.get_config(C.p, FILTERS, 'vault_filter_key', 'ANSIBLE_VAULT_FILTER_KEY', 'vault.key', ispath=True)
+ VAULT_FILTER_KEY = C.get_config(C.p, FILTERS, 'vault_filter_key', 'ANSIBLE_VAULT_FILTER_KEY', 'vault.key')
VAULT_FILTER_SALT = C.get_config(C.p, FILTERS, 'vault_filter_salt', 'ANSIBLE_VAULT_FILTER_SALT', None)
- VAULT_FILTER_ITERATIONS = C.get_config(C.p, FILTERS, 'vault_filter_iterations', 'ANSIBLE_VAULT_FILTER_ITERATIONS', 1000000, integer=True)
- VAULT_FILTER_GENERATE_KEY = C.get_config(C.p, FILTERS, 'vault_filter_generate_key', 'ANSIBLE_VAULT_GENERATE_KEY', False, boolean=True)
+ VAULT_FILTER_ITERATIONS = C.get_config(C.p, FILTERS, 'vault_filter_iterations', 'ANSIBLE_VAULT_FILTER_ITERATIONS', 1000000)
+ VAULT_FILTER_GENERATE_KEY = C.get_config(C.p, FILTERS, 'vault_filter_generate_key', 'ANSIBLE_VAULT_GENERATE_KEY', False)
```

**Comment by jeffschulthies** [comment]
I am having the exact same issue. This has caused me a lot of my pain during my upgrade from ansible 2.2 to ansible 2.3. 

Thanks for fix @mattlan.

**Comment by marcinhlybin** [comment]
Thanks for the issue. I made changes to support Ansible 2.4+.
By the way, Ansible introduced builtin inline vault support in version 2.3 (http://docs.ansible.com/ansible/latest/playbooks_vault.html#single-encrypted-variable)

You should consider refactoring your code.
